# Generated by Django 3.1.2 on 2021-09-29 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReporteSolicitudCredito',
            new_name='ReporteConfiguracion',
        ),
    ]
