# Generated by Django 3.1.2 on 2021-09-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_reporteconfiguracion_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteconfiguracion',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
