# Generated by Django 3.1.2 on 2021-01-16 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubrosocio',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='rubrosocio',
            name='socio',
        ),
        migrations.AddField(
            model_name='rubrosocio',
            name='cuotas',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='rubrosocio',
            name='descripcion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rubrosocio',
            name='fecha_ingreso',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='rubrosocio',
            name='servicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rubrosocio',
            name='estado',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rubrosocio',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.rubro'),
        ),
        migrations.AlterField(
            model_name='rubrosocio',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
