# Generated by Django 3.1.2 on 2021-02-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20210205_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restriccionclasecredito',
            name='tiempo_desde',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
