# Generated by Django 3.1.2 on 2021-02-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20210209_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restriccionclasecredito',
            name='tiempo_hasta',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
