# Generated by Django 3.1.2 on 2021-01-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_socio_rubros'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosTemporales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos_temporales')),
            ],
        ),
    ]
