# Generated by Django 3.1.2 on 2021-02-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_cuota_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='fecha_ingreso',
            field=models.DateField(auto_now=True),
        ),
    ]
