# Generated by Django 3.1.2 on 2021-01-22 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20210121_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.solicitudcredito'),
        ),
        migrations.DeleteModel(
            name='ClaseSolicitud',
        ),
    ]
