# Generated by Django 3.1.2 on 2021-02-11 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20210209_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='garante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='garante', to='sistema.socio'),
        ),
    ]
