# Generated by Django 3.1.2 on 2021-01-18 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_archivostemporales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArchivosTemporales',
            new_name='ArchivoTemporal',
        ),
    ]
