# Generated by Django 3.1.2 on 2021-04-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_remove_rubro_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasecredito',
            name='plazomax',
        ),
        migrations.RemoveField(
            model_name='clasecredito',
            name='tiempo_minimo_servicio',
        ),
        migrations.RemoveField(
            model_name='clasecredito',
            name='valdesde',
        ),
        migrations.RemoveField(
            model_name='clasecredito',
            name='valhasta',
        ),
        migrations.RemoveField(
            model_name='parametro',
            name='clasecredito',
        ),
        migrations.RemoveField(
            model_name='restriccionclasecredito',
            name='clasecredito',
        ),
        migrations.AddField(
            model_name='clasecredito',
            name='restricciones',
            field=models.ManyToManyField(to='sistema.RestriccionClaseCredito'),
        ),
    ]
