# Generated by Django 3.1.2 on 2021-01-18 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20210118_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivoTemporal',
        ),
    ]
