# Generated by Django 3.1.2 on 2021-01-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20210121_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credito',
            name='cuota',
        ),
        migrations.AddField(
            model_name='credito',
            name='cuota',
            field=models.ManyToManyField(to='sistema.Cuota'),
        ),
    ]
