# Generated by Django 3.1.2 on 2021-04-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20210405_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasecredito',
            name='autorizacion',
        ),
    ]
