# Generated by Django 3.1.2 on 2021-01-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_auto_20210121_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasecredito',
            name='tiempo_minimo_servicio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
