# Generated by Django 3.1.2 on 2021-04-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_remove_clasecredito_autorizacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restriccionclasecredito',
            old_name='valhasta',
            new_name='val_max',
        ),
        migrations.AddField(
            model_name='restriccionclasecredito',
            name='val_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
