# Generated by Django 3.1.2 on 2021-01-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_archivotemporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivotemporal',
            name='archivo',
            field=models.Field(blank=True, null=True),
        ),
    ]
