# Generated by Django 3.1.2 on 2021-04-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_auto_20210405_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='restriccionclasecredito',
            name='plazo_max',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restriccionclasecredito',
            name='plazo_min',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
