# Generated by Django 3.1.2 on 2021-01-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_auto_20210118_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivotemporal',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos_temporales'),
        ),
    ]
