# Generated by Django 3.1.2 on 2021-01-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_auto_20210123_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clasecredito',
            old_name='tiempo_minimo',
            new_name='tiempo_minimo_servicio',
        ),
    ]
