# Generated by Django 3.1.2 on 2021-04-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_auto_20210406_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restriccionclasecredito',
            old_name='tiempo_desde',
            new_name='tiempo_max',
        ),
        migrations.RenameField(
            model_name='restriccionclasecredito',
            old_name='tiempo_hasta',
            new_name='tiempo_min',
        ),
        migrations.AlterField(
            model_name='restriccionclasecredito',
            name='val_max',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restriccionclasecredito',
            name='val_min',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
