# Generated by Django 3.1.2 on 2021-01-19 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_auto_20210118_1717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivoTemporal',
        ),
    ]
