# Generated by Django 3.1.2 on 2021-01-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_auto_20210123_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubro',
            name='abreviatura',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rubro',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='tipo',
            field=models.CharField(max_length=10),
        ),
    ]
