# Generated by Django 3.1.2 on 2021-04-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_auto_20210406_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restriccionclasecredito',
            name='plazo_min',
        ),
    ]
