# Generated by Django 3.1.2 on 2021-01-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_auto_20210123_1147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestriccionesCredito',
        ),
    ]
