# Generated by Django 3.1.2 on 2021-04-22 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_remove_restriccionclasecredito_tiempo_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='aprobado_por',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aprobado_por', to='sistema.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='revisado_por',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='revisado_por', to='sistema.usuario'),
            preserve_default=False,
        ),
    ]
