# Generated by Django 3.1.2 on 2021-01-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0013_delete_restriccionescredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasecredito',
            name='parametros',
            field=models.ManyToManyField(blank=True, null=True, to='sistema.Parametro'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
