# Generated by Django 3.1.2 on 2021-04-23 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0013_auto_20210422_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aprobado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='revisado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
