# Generated by Django 3.1.2 on 2021-01-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0015_remove_clasecredito_parametros'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametro',
            name='clasecredito',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sistema.clasecredito'),
            preserve_default=False,
        ),
    ]
