# Generated by Django 3.1.2 on 2021-09-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0015_auto_20210422_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restriccionclasecredito',
            name='val_min',
        ),
    ]
