# Generated by Django 3.1.2 on 2021-01-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0016_parametro_clasecredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubro',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
