# Generated by Django 3.1.2 on 2021-01-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0017_auto_20210127_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='fecha_ingreso',
            field=models.DateField(auto_now=True),
        ),
    ]
