# Generated by Django 3.1.2 on 2021-01-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0018_credito_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasecredito',
            name='porcentaje_interes',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
