# Generated by Django 3.1.2 on 2021-01-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0019_clasecredito_porcentaje_interes'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='porcentaje_interes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='clasecredito',
            name='porcentaje_interes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
