# Generated by Django 3.1.2 on 2021-01-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0020_auto_20210129_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credito',
            old_name='interes',
            new_name='porcentaje_interes',
        ),
    ]
