# Generated by Django 3.1.2 on 2021-01-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0021_auto_20210129_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuota',
            old_name='monto',
            new_name='capital',
        ),
        migrations.AddField(
            model_name='cuota',
            name='interes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cuota',
            name='saldo_capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cuota',
            name='valor_cuota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
