# Generated by Django 3.1.2 on 2021-01-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0022_auto_20210129_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='orden',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
