# Generated by Django 3.1.2 on 2021-01-31 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0023_cuota_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacioncredito',
            name='estado',
        ),
    ]
