# Generated by Django 3.1.2 on 2021-01-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0024_remove_liquidacioncredito_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacioncredito',
            name='documento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
