from django.urls import path
from .views import *

app_name = 'sistema'

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('cambiarpassword/', cambiar_password, name='cambiarpassword'),
    path('asistentecreate/', AsistenteCreate.as_view(), name='asistentecreate'),
    path('asistenteupdate/<int:pk>/', AsistenteUpdate.as_view(), name='asistenteupdate'),
    path('presidentecreate/', PresidenteCreate.as_view(), name='presidentecreate'),
    # path('administradordetail/<int:pk>/', AdministradorDetailView.as_view(), name="administradordetail"),
    path('usuariodetail/<int:pk>/', UsuarioDetailView.as_view(), name="usuariodetail"),
    path('usuariolist/', UsuarioListView.as_view(), name="usuariolist"),
    path('usuariodelete/<int:pk>/', UsuarioDelete.as_view(), name='usuariodelete'),
    path('usuarioupdate/<int:pk>/', UsuarioUpdate.as_view(),
         name="usuarioupdate"),
    path('administradorcreate/', AdministradorCreate.as_view(), name='administradorcreate'),
    path('administradorupdate/<int:pk>/', AdministradorUpdate.as_view(), name='administradorupdate'),
    path('presidentecreate/', PresidenteCreate.as_view(), name='presidentecreate'),
    path('presidenteupdate/<int:pk>/', PresidenteUpdate.as_view(), name='presidenteupdate'),
    path('asistentecreate/', AsistenteCreate.as_view(), name='asistentecreate'),
    path('sociocreate/', SocioCreate.as_view(), name='sociocreate'),
    path('socioupdate/<int:pk>/', SocioUpdate.as_view(), name='socioupdate'),
    path('clasecreditolist/', ClaseCreditoListView.as_view(), name="clasecreditolist"),
    path('clasecreditodetail/<int:pk>/', ClaseCreditoDetailView.as_view(), name="clasecreditodetail"),
    path('clasecreditocreate/', ClaseCreditoCreate.as_view(), name='clasecreditocreate'),
    path('clasecreditoupdate/<int:pk>/', ClaseCreditoUpdate.as_view(), name='clasecreditoupdate'),
    path('clasecreditodelete/<int:pk>/', ClaseCreditoDelete.as_view(), name='clasecreditodelete'),
    # path('clasesolicitudlist/', ClaseSolicitudListView.as_view(), name="clasesolicitudlist"),
    # path('clasesolicituddetail/<int:pk>/', ClaseSolicitudDetailView.as_view(), name="clasesolicituddetail"),
    # path('clasesolicitudcreate/', ClaseSolicitudCreate.as_view(), name='clasesolicitudcreate'),
    # path('clasesolicitudupdate/<int:pk>/', ClaseSolicitudUpdate.as_view(), name='clasesolicitudupdate'),
    # path('clasesolicituddelete/<int:pk>/', ClaseSolicitudDelete.as_view(), name='clasesolicituddelete'),

    path('restriccionclasecreditolist/', RestriccionClaseCreditoListView.as_view(), name="restriccionclasecreditolist"),
    path('restriccionclasecreditocreate/', crear_restricciones_clase_credito,
         name="restriccionclasecreditocreate"),
    path('restriccionclasecreditoupdate/<int:pk>/', RestriccionClaseCreditoUpdate.as_view(),
         name='restriccionclasecreditoupdate'),
    path('restriccionclasecreditodelete/<int:pk>/', RestriccionClaseCreditoDelete.as_view(),
         name='restriccionclasecreditodelete'),
    path('rubrolist/', RubroListView.as_view(), name="rubrolist"),
    path('rubrodetail/<int:pk>/', RubroDetailView.as_view(),
         name="rubrodetail"),
    path('rubroupdate/<int:pk>/', RubroUpdate.as_view(),
         name="rubroupdate"),
    path('rubrocreate/', RubroCreate.as_view(), name="rubrocreate"),
    path('rubrodelete/<int:pk>/', RubroDelete.as_view(),
         name="rubrodelete"),
    path('cambiarpassword/', cambiar_password, name='cambiarpassword'),

]
